name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: leoai-nexus-data-lake
  REGION: us-central1
  SERVICE_NAME: next-vibemarketer
  IMAGE: us-central1-docker.pkg.dev/leoai-nexus-data-lake/next-vibemarketer/next-vibemarketer
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/635202209750/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider-v5
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          audience: https://iam.googleapis.com/projects/635202209750/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider-v5

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t ${{ env.IMAGE }}:${{ github.sha }} .
          docker push ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" \
            --allow-unauthenticated

      - name: Validate Deployment
        run: |
          chmod +x scripts/validate-deploy.sh
          ./scripts/validate-deploy.sh 